import Bytes from "bytes"
import Option from "option"
import Result from "result"
import Http from "suborbital/http"
import Log from "suborbital/log"

export let run: Bytes -> Result<Bytes, (Int32, String)> = input =>  {

  Log.info("👋 hello from Grain")

  let callAssemblyScript = Http.get("http://localhost:8088", None)

  match (callAssemblyScript) {
    Ok(value) => {
      Log.info(Bytes.toString(value))
    },
    Err(err) => Log.error("😡 ouch")
  }

  let callJavaScript = Http.get("http://localhost:8089", None)

  match (callJavaScript) {
    Ok(value) => {
      Log.info(Bytes.toString(value))
    },
    Err(err) => Log.error("😡 ouch")
  }

  Ok(Bytes.concat(Bytes.fromString("😃 👋 Hello "), input))
}
